import assert from 'node:assert/strict';
import { buildEvacuationPlan } from './evacuation-plan';
import type { DssData, DssPerson } from './dss.models';
const person=(id:string,family=id,zone='a',priority='High'):DssPerson=>({id,name:id,household:family,householdId:family,zone,zoneId:zone,address:'',priority,risk:'High',status:'For Evacuation',manualPriority:'High',vulnerabilities:[],details:[],assistance:[]});
const center=(id:string,spaces:number|null,zone='a',status='Available'):DssData['shelters'][number]=>({id,name:id,zone,zoneId:zone,location:'',capacity:spaces??10,occupancy:spaces===null?null:0,available:spaces,status});
const data={evacuation:[person('one','family'),person('two','family'),person('urgent','urgent','a','Highest'),{...person('already'),status:'Evacuated'}],shelters:[center('local',2),center('other',2,'b'),center('unknown',null),center('closed',10,'a','Unavailable')]} as DssData;
const original=JSON.stringify(data);
let plan=buildEvacuationPlan(data);
assert.equal(plan.assignments[0]!.person.id,'urgent','Highest priority household is placed first');
assert.equal(plan.suggested,3);assert.equal(plan.unplaced,0);
assert.equal(plan.assignments.find(a=>a.person.id==='one')!.shelter?.id,'other','Keep the family together when another zone has space');
assert.equal(plan.assignments.find(a=>a.person.id==='two')!.shelter?.id,'other');
assert.equal(plan.splitHouseholds,0);
assert.ok(plan.assignments.filter(a=>a.person.householdId==='family').every(a=>a.crossZone));
plan=buildEvacuationPlan(data,false);
assert.equal(plan.suggested,2);assert.equal(plan.unplaced,1);assert.equal(plan.splitHouseholds,1);
assert.ok([...plan.remaining.values()].every(n=>n>=0),'Never over-allocate');
assert.ok(plan.assignments.every(a=>a.shelter?.id!=='closed'&&a.shelter?.id!=='unknown'));
assert.equal(JSON.stringify(data),original,'Planning cannot mutate real assessment data');
assert.equal(buildEvacuationPlan({...data,shelters:[]}).unplaced,3);
assert.equal(buildEvacuationPlan({...data,evacuation:[]}).assignments.length,0);
assert.deepEqual(buildEvacuationPlan(data),buildEvacuationPlan(data),'Suggestions are deterministic');
console.log('PASS: priority ordering, household grouping, cross-zone choice, split warnings, capacity limits, unavailable/unknown exclusion, and immutable deterministic plans.');
