CREATE TABLE IF NOT EXISTS household_year_snapshots (
  snapshot_year SMALLINT UNSIGNED NOT NULL,
  household_id CHAR(36) NOT NULL,
  household_number VARCHAR(80) NOT NULL,
  zone_id CHAR(36) NOT NULL,
  zone_name VARCHAR(120) NOT NULL,
  address_line VARCHAR(255) NOT NULL,
  head_of_household_name VARCHAR(160) NOT NULL,
  contact_number VARCHAR(30) NULL,
  verification_status VARCHAR(40) NOT NULL,
  captured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (snapshot_year, household_id),
  INDEX household_snapshot_year_number_idx (snapshot_year, household_number),
  INDEX household_snapshot_year_zone_idx (snapshot_year, zone_id)
);

CREATE TABLE IF NOT EXISTS resident_year_snapshots (
  snapshot_year SMALLINT UNSIGNED NOT NULL,
  resident_id CHAR(36) NOT NULL,
  household_id CHAR(36) NOT NULL,
  household_number VARCHAR(80) NOT NULL,
  zone_id CHAR(36) NOT NULL,
  zone_name VARCHAR(120) NOT NULL,
  household_address VARCHAR(255) NOT NULL,
  head_of_household_name VARCHAR(160) NOT NULL,
  full_name VARCHAR(160) NOT NULL,
  date_of_birth DATE NOT NULL,
  sex VARCHAR(40) NOT NULL,
  contact_number VARCHAR(30) NULL,
  address_line VARCHAR(255) NOT NULL,
  vulnerability_type VARCHAR(100) NULL,
  vulnerability_other VARCHAR(160) NULL,
  relationship_to_head VARCHAR(60) NULL,
  relationship_other VARCHAR(160) NULL,
  marital_status VARCHAR(30) NULL,
  out_of_school_youth VARCHAR(5) NULL,
  occupation VARCHAR(160) NULL,
  education VARCHAR(160) NULL,
  philsys_number VARCHAR(80) NULL,
  philhealth_number VARCHAR(80) NULL,
  fp_use VARCHAR(5) NULL,
  unmet_needs VARCHAR(5) NULL,
  pwd_specify VARCHAR(160) NULL,
  solo_parent VARCHAR(5) NULL,
  morbidity VARCHAR(160) NULL,
  water_source_level VARCHAR(5) NULL,
  sanitary_toilet VARCHAR(10) NULL,
  can_swim VARCHAR(3) NULL,
  house_type VARCHAR(20) NULL,
  emergency_contact_name VARCHAR(160) NULL,
  emergency_contact_number VARCHAR(30) NULL,
  priority_level VARCHAR(20) NOT NULL,
  evacuation_status VARCHAR(40) NOT NULL,
  record_status VARCHAR(20) NOT NULL,
  evacuation_shelter_id CHAR(36) NULL,
  source_created_at DATETIME NOT NULL,
  source_updated_at DATETIME NOT NULL,
  captured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (snapshot_year, resident_id),
  INDEX resident_snapshot_year_household_idx (snapshot_year, household_id),
  INDEX resident_snapshot_year_zone_idx (snapshot_year, zone_id),
  INDEX resident_snapshot_year_name_idx (snapshot_year, full_name)
);
