import test from 'node:test';
import assert from 'node:assert/strict';
import { buildDss, assessRisk, vulnerabilities } from '../dist/dss.js';
import { dssQuery } from '../dist/dss-api.js';
const now=new Date('2026-09-16T04:00:00Z');
const person=(overrides={})=>({resident_id:'p1',household_id:'h1',full_name:'Test resident',date_of_birth:'1950-01-01',address_line:'Test address',vulnerability_type:null,vulnerability_other:null,pwd_specify:null,morbidity:null,can_swim:null,house_type:null,priority_level:'Low',evacuation_status:'Safe',...overrides});
const report=(id,severity='Major Incident',status='Validated')=>({report_id:id,tracking_code:id,location_text:'Test area',severity_level:severity,status,created_at:'2026-09-10 10:00:00',incident_type:'River Flooding'});
function fixture() {return {zones:[{zone_id:'z1',zone_name:'Zone 1'},{zone_id:'z2',zone_name:'Zone 2'}],households:[{household_id:'h1',household_number:'Z1-1',zone_id:'z1',head_of_household_name:'Test head',address_line:'Test address'}],residents:[person()],reports:[report('r1'),report('r2','Minor Incident')],reportZones:[{report_id:'r1',zone_id:'z1'},{report_id:'r2',zone_id:'z1'}],shelters:[]};}
test('empty database has unknown overall risk and empty lists',()=>{const d=buildDss({zones:[],households:[],residents:[],reports:[],reportZones:[],shelters:[]},{},now);assert.equal(d.overall.risk,null);assert.equal(d.metrics.residents,0);assert.deepEqual(d.evacuation,[]);assert.deepEqual(d.recommendations,[]);});
test('transparent boundaries and resolved/rejected reports never raise risk',()=>{
 assert.equal(assessRisk([],1),'Low');assert.equal(assessRisk([report('a','Major Incident','Resolved'),report('b','Major Incident','Rejected'),report('c','Major Incident','Submitted')],1),'Low');
 assert.equal(assessRisk([report('a','Information')],0),'Moderate');assert.equal(assessRisk([report('a','Minor Incident')],1),'Moderate');
 assert.equal(assessRisk([report('a','Minor Incident'),report('b','Minor Incident')],0),'High');assert.equal(assessRisk([report('a')],1),'High');
 assert.equal(assessRisk([report('a'),report('b')],0),'High');assert.equal(assessRisk([report('a'),report('b')],1),'Critical');
});
test('report-count rule raises three reports to High and five to Critical',()=>{
 const reports=Array.from({length:5},(_,i)=>report(`count-${i}`,'Information'));
 assert.equal(assessRisk(reports.slice(0,2),0),'Moderate');
 assert.equal(assessRisk(reports.slice(0,3),0),'High');
 assert.equal(assessRisk(reports,0),'Critical');
});
test('age boundaries and recorded PWD/morbidity without explicit vulnerability',()=>{
 assert.deepEqual(vulnerabilities(person({date_of_birth:'1966-09-17'}),'2026-09-16'),[]);
 assert.deepEqual(vulnerabilities(person({date_of_birth:'1966-09-16'}),'2026-09-16'),['Senior citizen']);
 assert.deepEqual(vulnerabilities(person({date_of_birth:'2008-09-17'}),'2026-09-16'),['Child']);
 assert.deepEqual(vulnerabilities(person({date_of_birth:'2008-09-16',pwd_specify:'N',morbidity:'None'}),'2026-09-16'),[]);
 assert.deepEqual(vulnerabilities(person({date_of_birth:'2000-01-01',pwd_specify:'POLIO',morbidity:'HPN'}),'2026-09-16'),['PWD','Morbidity']);
});
test('multiple report-zone links do not multiply residents or overall report counts',()=>{const s=fixture();s.reportZones.push({report_id:'r1',zone_id:'z1'},{report_id:'r1',zone_id:'z2'});const d=buildDss(s,{},now);assert.equal(d.incidents.total,2);assert.equal(d.metrics.residents,1);assert.equal(d.metrics.affectedZones,2);assert.equal(d.zones[0].activeReports,2);assert.equal(d.metrics.affectedVulnerable,1);});
test('highest priority first; evacuated people stay out of outstanding queue',()=>{const s=fixture();s.residents.push(person({resident_id:'p2',date_of_birth:'2000-01-01'}),person({resident_id:'p3',evacuation_status:'Evacuated'}));const d=buildDss(s,{},now);assert.equal(d.evacuation[0].priority,'Highest');assert.equal(d.evacuation[1].priority,'High');assert.equal(d.evacuation.length,2);assert.equal(d.vulnerable.length,2);assert.equal(d.priorityHouseholds[0].residents,2);});
test('resident filters change counts and demand but do not conceal critical zone risk',()=>{const s=fixture();s.residents.push(person({resident_id:'p2',date_of_birth:'2015-01-01',evacuation_status:'Evacuated'}));const d=buildDss(s,{vulnerability:'Child',evacuationStatus:'Evacuated'},now);assert.equal(d.metrics.residents,1);assert.equal(d.zones[0].risk,'Critical');assert.equal(d.evacuation.length,0);assert.equal(d.priorityHouseholds.length,0);});
test('date and severity filters recalculate risk, incidents and priority',()=>{const s=fixture();const none=buildDss(s,{from:'2026-09-11'},now);assert.equal(none.incidents.total,0);assert.equal(none.overall.risk,'Low');assert.equal(none.evacuation.length,0);const minor=buildDss(s,{severity:'Minor Incident'},now);assert.equal(minor.overall.risk,'Moderate');assert.equal(minor.evacuation[0].priority,'Medium');const boundary=buildDss(s,{from:'2026-09-10',to:'2026-09-10'},now);assert.equal(boundary.incidents.total,2);});
test('zone and risk filters constrain all linked sections',()=>{const s=fixture();s.shelters.push({shelter_id:'s1',shelter_name:'Test shelter',zone_id:'z1',location_text:'Test location',capacity:10,current_occupancy:0,status:'Available'});const d=buildDss(s,{risk:'Low'},now);assert.equal(d.zones.length,1);assert.equal(d.zones[0].id,'z2');assert.equal(d.metrics.residents,0);assert.equal(d.incidents.total,0);assert.equal(d.shelters.length,0);assert.equal(d.recommendations[0].zone,'Zone 2');const z=buildDss(s,{zone:'z1'},now);assert.equal(z.zones.length,1);assert.equal(z.shelters.length,1);});
test('unassigned active reports are explicit and are not assigned invented zones',()=>{const s=fixture();s.reports.push(report('unassigned'));const d=buildDss(s,{},now);assert.equal(d.incidents.unassignedActive,1);assert.equal(d.incidents.active,3);assert.match(d.overall.explanation,/incomplete/);assert.ok(d.recommendations.some(r=>r.zone==='Unassigned reports'));});
test('capacity uses operational spaces; unknown occupancy is not zero',()=>{const s=fixture();s.shelters=[{shelter_id:'s1',shelter_name:'Test shelter',zone_id:'z1',location_text:'Test location',capacity:10,current_occupancy:9,status:'Available'},{shelter_id:'s2',shelter_name:'Closed',zone_id:'z1',location_text:'Test location',capacity:100,current_occupancy:0,status:'Unavailable'},{shelter_id:'s3',shelter_name:'Unknown',zone_id:'z1',location_text:'Test location',capacity:50,current_occupancy:null,status:'Available'}];s.residents.push(person({resident_id:'p2'}));const d=buildDss(s,{},now);assert.equal(d.shelters[0].status,'Nearly Full');assert.equal(d.shelters[0].available,1);assert.equal(d.shelters[1].available,0);assert.equal(d.shelters[2].available,null);assert.ok(d.recommendations.some(r=>r.text.includes('2 priority residents versus 1')));assert.ok(d.recommendations.some(r=>r.text.includes('missing shelter occupancy')));});
test('unknown population is surfaced instead of claiming complete exposure',()=>{const s=fixture();s.residents=[];const d=buildDss(s,{},now);assert.equal(d.coverage.registeredPopulationKnown,false);assert.equal(d.zones[0].populationKnown,false);assert.deepEqual(d.coverage.missingPopulationZones,['Zone 1','Zone 2']);});
test('reject impossible dates, backwards date ranges, invalid enums and array query values',()=>{assert.equal(dssQuery.safeParse({from:'2026-02-30'}).success,false);assert.equal(dssQuery.safeParse({from:'2026-09-12',to:'2026-09-01'}).success,false);assert.equal(dssQuery.safeParse({risk:'Extreme'}).success,false);assert.equal(dssQuery.safeParse({severity:['Information']}).success,false);assert.equal(dssQuery.safeParse({from:'2026-09-10',risk:'Critical'}).success,true);});
