import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import { randomUUID } from 'node:crypto';
import { db } from './db.js';
import { config } from './config.js';
import { createAccessToken } from './auth.js';
import { colaclingBoundary, pointInsideGeometry } from './map-boundary.js';
import { canAdvanceResponse } from './response-management.js';

assert.ok(['localhost','127.0.0.1'].includes(new URL(config.databaseUrl).hostname),'Use a local test database.');
const zone=randomUUID(),household=randomUUID(),resident=randomUUID(),team=randomUUID();
const number=`Z99-${Date.now()}`,label=`Document check ${zone}`,year=2001;
const geometry={type:'Polygon',coordinates:[[[122.884,13.782],[122.886,13.782],[122.886,13.784],[122.884,13.784],[122.884,13.782]]]};
const responseKey=`household:${household}`;
const csv=`household_number,full_name,date_of_birth,sex,address_line,priority_level\n${number},${label},2000-01-01,Female,Colacling,Low`;
assert.deepEqual(JSON.parse(readFileSync(new URL('../../frontend/public/colacling-boundary.geojson',import.meta.url),'utf8')),colaclingBoundary,'Browser and API must use the same boundary.');
const square={type:'Polygon',coordinates:[[[0,0],[2,0],[2,2],[0,2],[0,0]],[[.5,.5],[1.5,.5],[1.5,1.5],[.5,1.5],[.5,.5]]]};
assert.equal(pointInsideGeometry(.25,.25,square),true);
assert.equal(pointInsideGeometry(1,1,square),false,'Exclude polygon holes.');
assert.equal(pointInsideGeometry(0,1,square),true,'Accept boundary points.');
assert.equal(pointInsideGeometry(1,3,square),false);
assert.equal(pointInsideGeometry(13.7828976,122.8852784,colaclingBoundary),true);
assert.equal(pointInsideGeometry(14.6,121,colaclingBoundary),false);
assert.equal(canAdvanceResponse('For Review','Completed'),false);
assert.equal(canAdvanceResponse('Pending','In Progress'),true);
try {
  const [users]=await db.query<any[]>("SELECT user_id,username,role,credential_version FROM users WHERE is_active=1 AND must_change_password=0 AND role IN ('Super Admin','Data Encoder')");
  const admin=users.find(u=>u.role==='Super Admin'),encoder=users.find(u=>u.role==='Data Encoder');assert.ok(admin);assert.ok(encoder);
  const request=async(path:string,method='GET',body?:unknown,expected=200,user:any=admin)=>{
    const response=await fetch(`http://localhost:${config.port}/api/${path}`,{method,headers:{'content-type':'application/json',...(user?{authorization:`Bearer ${createAccessToken({userId:user.user_id,username:user.username,role:user.role,credentialVersion:user.credential_version})}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});
    const text=await response.text();assert.equal(response.status,expected,`${method} ${path}: ${text}`);return text?JSON.parse(text):undefined;
  };
  await db.execute('INSERT INTO zones(zone_id,zone_name,polygon_geojson) VALUES(?,?,?)',[zone,label,JSON.stringify(geometry)]);
  await db.execute('INSERT INTO households(household_id,household_number,zone_id,address_line,head_of_household_name) VALUES(?,?,?,?,?)',[household,number,zone,'Colacling','Test household']);
  await db.execute("INSERT INTO residents(resident_id,household_id,full_name,date_of_birth,sex,address_line,evacuation_status) VALUES(?,?,?,'1950-01-01','Female','Colacling','For Evacuation')",[resident,household,label]);
  await db.execute('INSERT INTO rescue_teams(team_id,name,leader,contact,vehicle,passenger_capacity) VALUES(?,?,?, ?,NULL,2)',[team,label,'Test leader','Test radio']);
  const map=await request('map/live');assert.ok(map.boundary.features.length);
  const saved=await request(`barangay-zones/${zone}`);assert.deepEqual(typeof saved.polygon_geojson==='string'?JSON.parse(saved.polygon_geojson):saved.polygon_geojson,geometry);
  await request(`barangay-zones/${zone}`,'PUT',{zoneName:label,zoneColor:'#123456'} ,204);
  const unchanged=await request(`barangay-zones/${zone}`);assert.deepEqual(typeof unchanged.polygon_geojson==='string'?JSON.parse(unchanged.polygon_geojson):unchanged.polygon_geojson,geometry);
  await request('residents/import','POST',{csv,preview:true,year});
  await request('residents/import','POST',{csv,preview:false,year});
  await request('residents/import','POST',{csv,preview:false,year},400);
  const archive=await request(`residents/yearly?year=${year}&search=${encodeURIComponent(label)}`);assert.equal(archive.items.length,1);
  const liveYear=Number(new Intl.DateTimeFormat('en',{timeZone:'Asia/Manila',year:'numeric'}).format(new Date()));
  const [beforeReads]=await db.query<any[]>('SELECT * FROM resident_year_snapshots WHERE household_id=? ORDER BY snapshot_year,resident_id',[household]);
  const live=await request(`residents/yearly?year=${liveYear}&search=${encodeURIComponent(label)}&filter_vulnerable=true`);
  assert.equal(live.items[0].resident_id,resident);assert.equal(live.items[0].household_number,number);
  await request(`residents/yearly?year=${liveYear}&page=2&pageSize=1`);
  const [afterReads]=await db.query<any[]>('SELECT * FROM resident_year_snapshots WHERE household_id=? ORDER BY snapshot_year,resident_id',[household]);
  assert.deepEqual(afterReads,beforeReads,'Live reads must leave archives unchanged.');
  await request('residents/yearly/capture','POST',{confirmed:true},403,encoder);
  await request('residents/yearly/capture','POST',{},400);
  const [current]=await db.query<any[]>('SELECT resident_id FROM residents WHERE household_id=?',[household]);assert.equal(current.length,1,'Historical import must not write current residents.');
  const badCsv=csv.replace('2000-01-01','2002-01-01');await request('residents/import','POST',{csv:badCsv,preview:true,year},400);
  await request('residents/import','POST',{csv,preview:false,year:new Date().getFullYear()+1},400);
  const details=await request(`households/${household}/details`);
  const dss=await request('statistics/dss');assert.equal(details.members[0].priority,dss.evacuation.find((p:any)=>p.id===resident).priority);
  const shelter={shelterName:label,zoneId:zone,locationText:'Colacling',latitude:14.6,longitude:121,capacity:2,contactPerson:'Test person',contactNumber:'09123456789',status:'Available'};
  await request('shelters','POST',shelter,400);
  await request('response-actions','GET',undefined,401,null);
  let board=await request('response-actions');let action=board.items.find((i:any)=>i.source_key===responseKey);assert.ok(action);assert.equal(action.status,'For Review');
  await request('response-actions');const [duplicates]=await db.query<any[]>('SELECT COUNT(*) count FROM response_actions WHERE source_key=?',[responseKey]);assert.equal(duplicates[0].count,1);
  const update={teamId:team,status:'Pending',revision:0,note:'Official approved action',confirmed:false};
  await request(`response-actions/${responseKey}`,'PUT',update,403,encoder);
  await request(`response-actions/${responseKey}`,'PUT',{...update,status:'Completed',confirmed:true},400);
  await request(`response-actions/${responseKey}`,'PUT',update);
  await request(`response-actions/${responseKey}`,'PUT',update,409);
  await request(`response-actions/${responseKey}`,'PUT',{...update,revision:1,status:'In Progress',note:'Assigned team is assisting'});
  await request(`response-actions/${responseKey}`,'PUT',{...update,revision:2,status:'Completed'},400);
  await request(`response-actions/${responseKey}`,'PUT',{...update,revision:2,status:'Completed',confirmed:true,note:'Completion confirmed with assigned team'});
  board=await request('response-actions');action=board.items.find((i:any)=>i.source_key===responseKey);assert.equal(action.status,'Completed');assert.equal(action.history.length,3);
  await db.execute("UPDATE residents SET evacuation_status='Safe' WHERE resident_id=?",[resident]);
  board=await request('response-actions');action=board.items.find((i:any)=>i.source_key===responseKey);assert.equal(action.suggestionCurrent,false);assert.equal(action.status,'Completed');
  console.log('PASS: boundaries, preserved geometry, historical preview/import/duplicates/isolation, planner priorities, response permissions/transitions/conflicts/confirmation/history and refresh persistence.');
} finally {
  await db.execute('DELETE FROM response_action_updates WHERE source_key IN (?,?)',[responseKey,`zone:${zone}`]);
  await db.execute('DELETE FROM response_actions WHERE source_key IN (?,?)',[responseKey,`zone:${zone}`]);
  await db.execute('DELETE FROM rescue_teams WHERE team_id=?',[team]);
  await db.execute('DELETE FROM resident_year_snapshots WHERE household_id=?',[household]);
  await db.execute('DELETE FROM household_year_snapshots WHERE household_id=?',[household]);
  await db.execute('DELETE FROM residents WHERE resident_id=?',[resident]);
  await db.execute('DELETE FROM households WHERE household_id=?',[household]);
  await db.execute('DELETE FROM zones WHERE zone_id=?',[zone]);
  await db.end();
}
