import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db} from './db.js';
import {config} from './config.js';
import {createAccessToken} from './auth.js';
import {missionTransitions} from './rescue.js';

assert.ok(['localhost','127.0.0.1'].includes(new URL(config.databaseUrl).hostname),'Use the local development database only.');
const zone=randomUUID(),household=randomUUID(),shelter=randomUUID(),people=[randomUUID(),randomUUID(),randomUUID()];
const responders=[randomUUID(),randomUUID(),randomUUID()];
const assistanceId=randomUUID();
const label=`Rescue verification ${zone}`;const teamIds:string[]=[];
try{
  const [admins]=await db.query<any[]>("SELECT user_id,username,role,credential_version FROM users WHERE is_active=1 AND must_change_password=0 AND role='Super Admin' LIMIT 1");assert.ok(admins[0]);const admin=admins[0];
  const headers={'content-type':'application/json',authorization:`Bearer ${createAccessToken({userId:admin.user_id,username:admin.username,role:admin.role,credentialVersion:admin.credential_version})}`};
  const request=async(path:string,method='GET',body?:unknown,expected=200,auth=true)=>{
    const response=await fetch(`http://localhost:${config.port}/api/${path}`,{method,headers:auth?headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
    const result=await response.text();assert.equal(response.status,expected,`${method} ${path}: ${result}`);return result?JSON.parse(result):undefined;
  };
  await db.execute('INSERT INTO zones(zone_id,zone_name,polygon_geojson) VALUES(?,?,?)',[zone,label,JSON.stringify({type:'Polygon',coordinates:[[[.9,.9],[1.1,.9],[1.1,1.1],[.9,1.1],[.9,.9]]]})]);
  await db.execute('INSERT INTO households(household_id,household_number,zone_id,address_line,head_of_household_name) VALUES(?,?,?,?,?)',[household,label,zone,'Test pickup only','Test household']);
  for(const [i,id] of people.entries())await db.execute("INSERT INTO residents(resident_id,household_id,full_name,date_of_birth,sex,address_line,evacuation_status) VALUES(?,?,?,'1950-01-01','Female','Test pickup only','For Evacuation')",[id,household,`Test rescue person ${i}`]);
  await db.execute('INSERT INTO shelters(shelter_id,shelter_name,zone_id,location_text,latitude,longitude,capacity,contact_person,contact_number) VALUES(?,?,?,?,1,1,2,?,?)',[shelter,label,zone,'Test center only','Test contact','Test radio']);
  for(const [i,id] of responders.entries())await db.execute('INSERT INTO volunteers(volunteer_id,full_name,contact_number,responder_type) VALUES(?,?,?,?)',[id,label+' responder '+i,'Test radio',i===1?'Barangay Tanod':'Volunteer']);
  await request('rescue','GET',undefined,401,false);
  await request('rescue/teams','POST',{name:label,leaderId:responders[0],memberIds:responders.slice(0,2),vehicle:label,passengerCapacity:0},400);
  for(const i of [0,1])await request('rescue/teams','POST',{name:`${label} ${i}`,leaderId:i?responders[2]:responders[0],memberIds:i?[responders[2]]:responders.slice(0,2),vehicle:`${label} vehicle ${i}`,passengerCapacity:i?1:2},201);
  const board=()=>request('rescue');
  teamIds.push(...(await board()).teams.filter((t:any)=>t.name.startsWith(label)).map((t:any)=>t.team_id));assert.equal(teamIds.length,2);
  const teams=(await board()).teams.filter((t:any)=>teamIds.includes(t.team_id)).sort((a:any,b:any)=>b.passenger_capacity-a.passenger_capacity);
  await request('rescue/teams','POST',{name:`${label} shared`,leaderId:responders[0],memberIds:responders.slice(0,2),vehicle:`${label} shared vehicle`,passengerCapacity:2},201);
  const shared=(await board()).teams.find((t:any)=>t.name===`${label} shared`);
  await request(`rescue/teams/${teams[0].team_id}`,'PUT',{name:teams[0].name,leaderId:responders[0],memberIds:responders.slice(0,2),vehicle:teams[0].vehicle,passengerCapacity:2});
  await request('rescue/teams','POST',{name:`${label} duplicate`,leaderId:responders[0],memberIds:responders.slice(0,2),vehicle:teams[0].vehicle,passengerCapacity:2},409);
  const dispatch=(ids:string[],teamId=teams[0].team_id)=>({teamId,shelterId:shelter,residentIds:ids,pickup:'Test pickup only',instructions:'Test wheelchair assistance',expectedStatuses:Object.fromEntries(ids.map(id=>[id,'For Evacuation']))});
  await request('rescue/missions','POST',dispatch(people),409);
  await request('rescue/missions','POST',dispatch(people.slice(0,2),teams[1].team_id),409);
  await request('rescue/missions','POST',{...dispatch(people.slice(0,2)),expectedStatuses:{}},409);
  await db.execute("INSERT INTO assistance_requests(request_id,resident_id,household_id,submitted_by_user_id,kind,location,needs) VALUES(?,?,?,?,'Need help','Test pickup only','Test rescue assistance')",[assistanceId,people[2],household,admin.user_id]);
  const assistanceRequest={requestId:assistanceId,revision:0,confirmed:true};
  await request('rescue/missions','POST',{...dispatch([people[2]!]),assistanceRequest:{...assistanceRequest,confirmed:false}},400);
  await request('rescue/missions','POST',{...dispatch([people[2]!]),assistanceRequest:{...assistanceRequest,revision:1}},409);
  await request('rescue/missions','POST',{...dispatch([people[0]!]),assistanceRequest},400);
  await db.execute("UPDATE assistance_requests SET status='Closed' WHERE request_id=?",[assistanceId]);
  await request('rescue/missions','POST',{...dispatch([people[2]!]),assistanceRequest},409);
  await db.execute("UPDATE assistance_requests SET status='Submitted' WHERE request_id=?",[assistanceId]);
  const id=(await request('rescue/missions','POST',dispatch(people.slice(0,2)),201)).missionId;
  const summary=await request('rescue/summary');
  assert.ok(people.slice(0,2).every(p=>summary.summary.assignedResidentIds.includes(p)));
  assert.deepEqual(summary.missions,[]);assert.deepEqual(summary.outcomes,[]);
  const teamPage=await request(`rescue/teams?search=${encodeURIComponent(label)}&pageSize=1&sortBy=name&sortOrder=asc`);
  assert.equal(teamPage.totalItems,3);assert.equal(teamPage.items.length,1);assert.ok(teamPage.items[0].members.length);
  const nextTeamPage=await request(`rescue/teams?search=${encodeURIComponent(label)}&pageSize=1&page=2&sortBy=name&sortOrder=asc`);
  assert.notEqual(teamPage.items[0].team_id,nextTeamPage.items[0].team_id);
  await request('rescue/teams?sortBy=unknown', 'GET',undefined,400);
  await request(`volunteers/${responders[0]}`,'DELETE',undefined,409);
  assert.equal((await board()).teams.find((t:any)=>t.team_id===teams[0].team_id).active_mission_id,id);
  await request('rescue/missions','POST',dispatch([people[2]!]),409);
  assert.ok((await request('rescue/missions','POST',dispatch([people[2]!],shared.team_id),409)).message.includes('volunteer or tanod'));
  await request('rescue/missions','POST',dispatch([people[0]!],teams[1].team_id),409);
  await request(`rescue/teams/${teams[0].team_id}/availability`,'PUT',{availability:'Out of service'},409);
  await request(`rescue/teams/${teams[0].team_id}`,'PUT',{name:teams[0].name,leaderId:responders[0],memberIds:responders.slice(0,2),vehicle:teams[0].vehicle,passengerCapacity:2},409);
  await request(`residents/${people[0]}`,'DELETE',undefined,409);
  await request(`shelters/${shelter}`,'DELETE',undefined,409);
  await request(`shelters/${shelter}/assignments`,'POST',{residentIds:[people[0]],evacuationAt:new Date().toISOString()},409);
  const mission=async(missionId=id)=>(await board()).missions.find((m:any)=>m.mission_id===missionId);
  const update=async(status:string,extra={},expected=200,missionId=id)=>request(`rescue/missions/${missionId}/status`,'POST',{revision:(await mission(missionId)).revision,status,...extra},expected);
  await update('Arrived',{confirmedArrival:true},409);
  await update('Blocked',{},400);
  await update('At pickup');await request(`rescue/missions/${id}/status`,'POST',{revision:1,status:'Transporting'},409);
  await update('Transporting');await update('Arrived',{},400);
  const outcome={outcome:'Missing',revision:0,source:'Fictional field report',notes:'Fictional resident not located; review mission',lastSeenLocation:'Fictional pickup',observedAt:new Date().toISOString(),confirmed:true};
  await request(`rescue/outcomes/${people[0]}`,'POST',outcome);
  await update('Arrived',{confirmedArrival:true},409);
  assert.equal((await mission()).residents.find((r:any)=>r.id===people[0]).outcome,'Missing');
  await request(`rescue/outcomes/${people[0]}`,'POST',{...outcome,outcome:'Located',revision:1,notes:'Fictional resident located'});
  await request(`residents/${people[0]}`,'PUT',{evacuationStatus:'For Evacuation'},204);
  await db.execute('UPDATE shelters SET capacity=1 WHERE shelter_id=?',[shelter]);
  await update('Arrived',{confirmedArrival:true},409);
  const [notArrived]=await db.query<any[]>('SELECT evacuation_status FROM residents WHERE resident_id IN (?)',[people]);assert.ok(notArrived.every(r=>r.evacuation_status==='For Evacuation'));
  assert.equal((await mission()).status,'Transporting');
  await db.execute('UPDATE shelters SET capacity=2 WHERE shelter_id=?',[shelter]);
  await update('Arrived',{confirmedArrival:true,note:'Test group physically arrived'});
  const [arrived]=await db.query<any[]>('SELECT evacuation_status,evacuation_shelter_id FROM residents WHERE resident_id IN (?)',[people.slice(0,2)]);assert.ok(arrived.every(r=>r.evacuation_status==='Evacuated'&&r.evacuation_shelter_id===shelter));
  const [centers]=await db.query<any[]>('SELECT status,current_occupancy FROM shelters WHERE shelter_id=?',[shelter]);assert.equal(centers[0].current_occupancy,2);assert.equal(centers[0].status,'Full');
  assert.equal((await board()).teams.find((t:any)=>t.team_id===teams[0].team_id).active_mission_id,null);
  const finished=await mission();assert.equal(finished.updates.length,4);assert.ok(finished.updates.every((u:any)=>u.recorded_by==='System Super Admin'||u.recorded_by));assert.equal(missionTransitions.Arrived!.length,0);
  const [history]=await db.query<any[]>('SELECT * FROM evacuation_assignments WHERE resident_id IN (?)',[people.slice(0,2)]);assert.equal(history.length,2);
  await db.execute("UPDATE shelters SET capacity=3,status='Available' WHERE shelter_id=?",[shelter]);
  // Concurrent officials cannot send two teams for the same resident.
  const concurrent=await Promise.all(teams.map((t:any)=>fetch(`http://localhost:${config.port}/api/rescue/missions`,{method:'POST',headers,body:JSON.stringify(dispatch([people[2]!],t.team_id))})));
  assert.deepEqual(concurrent.map(r=>r.status).sort(),[201,409]);
  const activeId=(await Promise.all(concurrent.map(r=>r.json()))).find(r=>r.missionId).missionId;
  await update('Blocked',{note:'Test blocked road'},200,activeId);
  await update('Dispatched',{note:'Test road reopened'},200,activeId);
  await update('Cancelled',{},400,activeId);
  await update('Cancelled',{note:'Test mission no longer required'},200,activeId);
  assert.equal((await mission(activeId)).status,'Cancelled');
  const [released]=await db.query<any[]>('SELECT * FROM rescue_active_residents WHERE resident_id=?',[people[2]]);assert.equal(released.length,0);
  await request(`rescue/teams/${teams[0].team_id}/availability`,'PUT',{availability:'Out of service'});
  await request('rescue/missions','POST',dispatch([people[2]!]),409);
  // No-vehicle crews share neither a fictitious vehicle ID nor a seat limit.
  for(const i of [0,1])await request('rescue/teams','POST',{name:`${label} foot ${i}`,leaderId:responders[0],memberIds:responders.slice(0,2)},201);
  const footTeams=(await board()).teams.filter((t:any)=>t.name.includes(`${label} foot`));assert.equal(footTeams.length,2);assert.ok(footTeams.every((t:any)=>t.vehicle===null&&t.passenger_capacity===0));
  await request(`rescue/teams/${footTeams[1].team_id}`,'PUT',{name:footTeams[1].name,leaderId:responders[0],memberIds:responders.slice(0,2),vehicle:'',passengerCapacity:99});
  assert.equal((await board()).teams.find((t:any)=>t.team_id===footTeams[1].team_id).passenger_capacity,0);
  const footId=(await request('rescue/missions','POST',{...dispatch([people[2]!],footTeams[0].team_id),assistanceRequest},201)).missionId;
  const [[reviewedHelp]]=await db.query<any[]>('SELECT status,revision,review_note FROM assistance_requests WHERE request_id=?',[assistanceId]);assert.equal(reviewedHelp.status,'Acknowledged');assert.equal(reviewedHelp.revision,1);assert.ok(reviewedHelp.review_note.includes(footId));
  const [[helpAudit]]=await db.query<any[]>('SELECT recorded_by_user_id FROM assistance_request_updates WHERE request_id=?',[assistanceId]);assert.equal(helpAudit.recorded_by_user_id,admin.user_id);
  assert.equal((await mission(footId)).team_snapshot.vehicle,null);
  await request('rescue/missions','POST',dispatch([people[2]!],footTeams[1].team_id),409);
  await update('At pickup',{},200,footId);await update('Transporting',{},200,footId);
  await update('Arrived',{},400,footId);await update('Arrived',{confirmedArrival:true},200,footId);
  assert.equal((await mission(footId)).status,'Arrived');
  const [onFoot]=await db.query<any[]>('SELECT evacuation_status,evacuation_shelter_id FROM residents WHERE resident_id=?',[people[2]]);assert.equal(onFoot[0].evacuation_status,'Evacuated');assert.equal(onFoot[0].evacuation_shelter_id,shelter);
  // A mixed mission admits only actual arrivals; every exclusion needs a sourced outcome.
  await db.query("UPDATE residents SET evacuation_status='For Evacuation',evacuation_shelter_id=NULL WHERE resident_id IN (?)",[people]);
  await db.execute("UPDATE shelters SET capacity=3,current_occupancy=0,status='Available' WHERE shelter_id=?",[shelter]);
  const mixedId=(await request('rescue/missions','POST',dispatch(people,footTeams[0].team_id),201)).missionId;
  await update('At pickup',{},200,mixedId);await update('Transporting',{},200,mixedId);
  await update('Arrived',{confirmedArrival:true,arrivalResidentIds:[people[2]]},409,mixedId);
  await update('Arrived',{confirmedArrival:true,arrivalResidentIds:[randomUUID()]},400,mixedId);
  await request(`rescue/outcomes/${people[0]}`,'POST',{...outcome,revision:2});
  await request(`rescue/outcomes/${people[1]}`,'POST',{...outcome,outcome:'Deceased',revision:0,notes:'Fictional authorized confirmation'});
  await update('Arrived',{confirmedArrival:true,arrivalResidentIds:[people[0],people[2]]},409,mixedId);
  await db.execute('UPDATE shelters SET capacity=1 WHERE shelter_id=?',[shelter]);
  await update('Arrived',{confirmedArrival:true,arrivalResidentIds:[people[2]],note:'One resident physically arrived; two sourced outcomes recorded'},200,mixedId);
  const mixed=await mission(mixedId);
  assert.deepEqual(mixed.residents.map((r:any)=>r.arrivalStatus).sort(),['Arrived','Deceased','Missing']);
  const [mixedResidents]=await db.query<any[]>('SELECT resident_id,evacuation_status,evacuation_shelter_id FROM residents WHERE resident_id IN (?)',[people]);
  assert.ok(mixedResidents.filter(r=>r.resident_id!==people[2]).every(r=>r.evacuation_status!=='Evacuated'&&r.evacuation_shelter_id===null));
  const [mixedCenter]=await db.query<any[]>('SELECT current_occupancy FROM shelters WHERE shelter_id=?',[shelter]);assert.equal(mixedCenter[0].current_occupancy,1);
  assert.equal((await board()).teams.find((t:any)=>t.team_id===footTeams[0].team_id).active_mission_id,null);
  // Later outcome reporting preserves the past arrival snapshot, but removes current occupancy.
  await request(`rescue/outcomes/${people[2]}`,'POST',{...outcome,outcome:'Deceased',revision:0,notes:'Fictional report after arrival'});
  assert.equal((await mission(mixedId)).residents.find((r:any)=>r.id===people[2]).arrivalStatus,'Arrived');
  const [afterOutcome]=await db.query<any[]>('SELECT current_occupancy FROM shelters WHERE shelter_id=?',[shelter]);assert.equal(afterOutcome[0].current_occupancy,0);
  const outcomePage=await request(`rescue/outcomes?search=${encodeURIComponent('Test rescue person')}&filter_status=Deceased&pageSize=1`);
  assert.equal(outcomePage.items.length,1);assert.deepEqual(outcomePage.items[0].history,[]);
  assert.ok((await request(`rescue/outcomes/${people[0]}`)).history.length);
  const archiveLabel=`${label} archived`;
  for(let i=0;i<31;i++)await db.execute("INSERT INTO rescue_missions(mission_id,team_id,shelter_id,pickup,instructions,status,residents,team_snapshot,shelter_name,created_at,updated_at) VALUES(?,?,?,?,'','Cancelled','[]',?,?,'2000-01-01','2000-01-01')",[randomUUID(),teams[0].team_id,shelter,archiveLabel,JSON.stringify(teams[0]),label]);
  const archivedPage=await request(`rescue/missions?search=${encodeURIComponent(archiveLabel)}&filter_status=Completed&sortBy=updated&pageSize=20`);
  const olderPage=await request(`rescue/missions?search=${encodeURIComponent(archiveLabel)}&filter_status=Completed&sortBy=updated&pageSize=20&page=2`);
  assert.equal(archivedPage.totalItems,31);assert.equal(archivedPage.items.length,20);assert.equal(olderPage.items.length,11);
  assert.equal(new Set([...archivedPage.items,...olderPage.items].map(m=>m.mission_id)).size,31);
  assert.deepEqual(archivedPage.items[0].updates,[]);
  assert.ok((await request(`rescue/missions/${mixedId}`)).updates.length);
  const activePage=await request(`rescue/missions?search=${encodeURIComponent(archiveLabel)}&filter_status=Active`);assert.equal(activePage.totalItems,0);
  console.log('PASS: rescue transitions, no-vehicle teams, concurrency, capacity, mixed arrival/outcome safeguards, historical arrival snapshots, and occupancy after later outcomes.');
}finally{
  await db.execute('DELETE FROM assistance_request_updates WHERE request_id=?',[assistanceId]);
  await db.execute('DELETE FROM assistance_requests WHERE request_id=?',[assistanceId]);
  const [missions]=await db.query<any[]>('SELECT mission_id FROM rescue_missions WHERE shelter_id=?',[shelter]);
  if(missions.length){const ids=missions.map(m=>m.mission_id);await db.query('DELETE FROM rescue_active_responders WHERE mission_id IN (?)',[ids]);await db.query('DELETE FROM rescue_updates WHERE mission_id IN (?)',[ids]);await db.query('DELETE FROM rescue_active_residents WHERE mission_id IN (?)',[ids]);await db.query('DELETE FROM rescue_missions WHERE mission_id IN (?)',[ids]);}
  await db.query('DELETE FROM rescue_team_members WHERE volunteer_id IN (?)',[responders]);
  await db.query('DELETE FROM volunteers WHERE volunteer_id IN (?)',[responders]);
  await db.query('DELETE FROM rescue_teams WHERE name LIKE ?',[`${label}%`]);
  await db.query('DELETE FROM evacuation_assignments WHERE resident_id IN (?)',[people]);
  await db.query('DELETE FROM resident_outcome_updates WHERE resident_id IN (?)',[people]);await db.query('DELETE FROM resident_outcomes WHERE resident_id IN (?)',[people]);
  await db.query('DELETE FROM resident_year_snapshots WHERE resident_id IN (?)',[people]);await db.query('DELETE FROM residents WHERE resident_id IN (?)',[people]);
  await db.execute('DELETE FROM household_year_snapshots WHERE household_id=?',[household]);await db.execute('DELETE FROM households WHERE household_id=?',[household]);
  await db.execute('DELETE FROM shelters WHERE shelter_id=?',[shelter]);await db.execute('DELETE FROM zones WHERE zone_id=?',[zone]);await db.end();
  console.log('Isolated rescue verification records removed.');
}
