import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db} from './db.js';
import {config} from './config.js';
import {createAccessToken} from './auth.js';

assert.ok(['localhost','127.0.0.1'].includes(new URL(config.databaseUrl).hostname), 'Use a local test database.');
const zone=randomUUID(), household=randomUUID(), resident=randomUUID(),otherResident=randomUUID();
const label=`Resident account ${randomUUID()}`, username=`resident-${randomUUID()}`;
const initialPassword='InitialPassword123', newPassword='ReplacementPassword123';
let userId='', reportId='';
const request=async(path:string,method='GET',body?:unknown,token?:string,status=200)=>{
  const response=await fetch(`http://localhost:${config.port}/api/${path}`,{method,headers:{...(body instanceof FormData?{}:{'content-type':'application/json'}),...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});
  const text=await response.text(); assert.equal(response.status,status,`${method} ${path}: ${text}`);
  return {data:text?JSON.parse(text):null,cookie:response.headers.get('set-cookie')?.split(';')[0]};
};
try {
  const [admins]=await db.query<any[]>("SELECT user_id,username,role,credential_version FROM users WHERE role='Super Admin' AND is_active=1 AND must_change_password=0 LIMIT 1");
  assert.ok(admins[0]); const admin=createAccessToken({userId:admins[0].user_id,username:admins[0].username,role:admins[0].role,credentialVersion:admins[0].credential_version});
  await db.execute('INSERT INTO zones(zone_id,zone_name,polygon_geojson) VALUES(?,?,?)',[zone,label,JSON.stringify({type:'Polygon',coordinates:[[[122.884,13.782],[122.886,13.782],[122.886,13.784],[122.884,13.784],[122.884,13.782]]]})]);
  await db.execute("INSERT INTO households(household_id,household_number,zone_id,address_line,head_of_household_name,verification_status) VALUES(?,?,?,?,?,'Verified')",[household,label,zone,'Colacling','Test head']);
  await db.execute("INSERT INTO residents(resident_id,household_id,full_name,date_of_birth,sex,address_line,contact_number) VALUES(?,?,?,'2000-01-01','Female','Colacling','09123456789')",[resident,household,label]);
  const input={fullName:label,username,email:`${username}@example.com`,role:'Resident',residentId:resident,password:initialPassword};
  await request('flood-reports','POST',new FormData(),undefined,401);
  await request('flood-reports','POST',new FormData(),admin,403);
  await request('users','POST',{...input,residentId:''},admin,400);
  await db.execute("UPDATE households SET verification_status='Pending Verification' WHERE household_id=?",[household]);
  await request('users','POST',input,admin,400);
  await db.execute("UPDATE households SET verification_status='Verified' WHERE household_id=?",[household]);
  userId=(await request('users','POST',input,admin,201)).data.userId;
  await request('users','POST',{...input,username:`duplicate-${randomUUID()}`,email:`${randomUUID()}@example.com`},admin,400);
  const login=await request('auth/login','POST',{username,password:initialPassword});
  assert.equal(login.data.user.mustChangePassword,true);
  await request('flood-reports','POST',new FormData(),login.data.accessToken,403);
  const me=(await request('auth/me','GET',undefined,login.data.accessToken)).data;
  assert.equal(me.resident.resident_id,resident); assert.equal(me.resident.household_number,label);
  assert.equal(me.password_hash,undefined); assert.equal(me.resident.philsys_number,null);
  await request('auth/change-password','POST',{currentPassword:'incorrect',newPassword},login.data.accessToken,400);
  const changed=await request('auth/change-password','POST',{currentPassword:initialPassword,newPassword},login.data.accessToken);
  let token=changed.data.accessToken; assert.equal(changed.data.user.mustChangePassword,false);
  await request('auth/me','GET',undefined,login.data.accessToken,401);
  for (const path of ['users','residents','dashboard/summary','statistics/dss','rescue','response-actions','flood-reports']) await request(path,'GET',undefined,token,403);
  const profile={fullName:'Updated '+label,dateOfBirth:'2001-02-03',sex:'Female',email:`updated-${randomUUID()}@example.test`,contactNumber:'09987654321',addressLine:'Updated address, Colacling',emergencyContactName:'Emergency contact',emergencyContactNumber:'09123456789',occupation:'Teacher',education:'College',maritalStatus:'Single',philsysNumber:'TEST-PHILSYS',philhealthNumber:'TEST-PHILHEALTH',sanitaryToilet:'With',houseType:'Concrete',pwdSpecify:'Mobility impairment',canSwim:'No',soloParent:'Yes'};
  await request('auth/profile','PUT',profile,undefined,401);
  await request('auth/profile','PUT',profile,admin,403);
  await request('auth/profile','PUT',profile,login.data.accessToken,401);
  for(const extra of [{residentId:otherResident},{userId:admins[0].user_id},{householdId:randomUUID()},{role:'Super Admin'},{recordStatus:'Inactive'},{verificationStatus:'Verified'},{priorityLevel:'High'},{evacuationStatus:'Evacuated'},{status:'Approved'}])await request('auth/profile','PUT',{...profile,...extra},token,400);
  await request('auth/profile','PUT',{...profile,dateOfBirth:'2001-02-30'},token,400);
  await request('auth/profile','PUT',{...profile,contactNumber:'invalid'},token,400);
  await request('auth/profile','PUT',{...profile,emergencyContactNumber:'-------'},token,400);
  const [adminEmail]=await db.query<any[]>('SELECT email FROM users WHERE user_id=?',[admins[0].user_id]);
  await request('auth/profile','PUT',{...profile,email:adminEmail[0].email},token,400);
  await db.execute("INSERT INTO residents(resident_id,household_id,full_name,date_of_birth,sex,address_line) VALUES(?,?,?,'2001-02-03','Male','Colacling')",[otherResident,household,'Other '+label]);
  await request('auth/profile','PUT',{...profile,fullName:'Other '+label},token,409);
  for(const invalid of [{sanitaryToilet:'Maybe'},{houseType:'Tent'},{canSwim:'Sometimes'},{soloParent:'Unknown'},{philsysNumber:'x'.repeat(81)},{philhealthNumber:'x'.repeat(81)},{pwdSpecify:'x'.repeat(161)}])await request('auth/profile','PUT',{...profile,...invalid},token,400);
  await request('auth/profile','PUT',profile,token);
  const updatedMe=(await request('auth/me','GET',undefined,token)).data;
  assert.equal(updatedMe.fullName,profile.fullName);assert.equal(updatedMe.email,profile.email);
  assert.equal(updatedMe.resident.full_name,profile.fullName);assert.equal(updatedMe.resident.date_of_birth,profile.dateOfBirth);assert.equal(updatedMe.resident.contact_number,profile.contactNumber);assert.equal(updatedMe.resident.emergency_contact_name,profile.emergencyContactName);assert.equal(updatedMe.resident.occupation,profile.occupation);assert.equal(updatedMe.resident.household_number,label);
  for(const [field,value] of Object.entries({philsys_number:profile.philsysNumber,philhealth_number:profile.philhealthNumber,sanitary_toilet:profile.sanitaryToilet,house_type:profile.houseType,pwd_specify:profile.pwdSpecify,can_swim:profile.canSwim,solo_parent:profile.soloParent}))assert.equal(updatedMe.resident[field],value);
  const legacyProfile={...profile} as Record<string,unknown>;for(const key of ['philsysNumber','philhealthNumber','sanitaryToilet','houseType','pwdSpecify','canSwim','soloParent'])delete legacyProfile[key];
  await request('auth/profile','PUT',legacyProfile,token);
  assert.equal((await request('auth/me','GET',undefined,token)).data.resident.philsys_number,profile.philsysNumber,'Omitted new fields must be preserved');
  await request('auth/profile','PUT',{...profile,philsysNumber:'',philhealthNumber:'',sanitaryToilet:'',houseType:'',pwdSpecify:'',canSwim:'',soloParent:''},token);
  const clearedExtras=(await request('auth/me','GET',undefined,token)).data.resident;for(const key of ['philsys_number','philhealth_number','sanitary_toilet','house_type','pwd_specify','can_swim','solo_parent'])assert.equal(clearedExtras[key],null);
  const [other]=await db.query<any[]>('SELECT full_name FROM residents WHERE resident_id=?',[otherResident]);assert.equal(other[0].full_name,'Other '+label);
  await request('auth/profile','PUT',{...profile,emergencyContactName:'',emergencyContactNumber:'',occupation:'',education:'',maritalStatus:''},token);
  const [cleared]=await db.query<any[]>('SELECT emergency_contact_name,occupation,education,marital_status FROM residents WHERE resident_id=?',[resident]);assert.equal(cleared[0].emergency_contact_name,null);assert.equal(cleared[0].occupation,null);
  const form=new FormData();
  for(const [key,value] of Object.entries({reporterName:'Spoofed identity',reporterContactInfo:'Spoofed contact',locationText:'Colacling',incidentType:'Road Flooding',severityLevel:'Information',latitude:'13.7828976',longitude:'122.8852784',description:'Account integration check'})) form.set(key,value);
  reportId=(await request('flood-reports','POST',form,token,201)).data.reportId;
  const [reports]=await db.query<any[]>('SELECT * FROM flood_reports WHERE report_id=?',[reportId]);
  assert.equal(reports[0].reporter_user_id,userId); assert.equal(reports[0].reporter_name,profile.fullName); assert.equal(reports[0].reporter_contact_info,profile.contactNumber); assert.equal(reports[0].status,'Submitted');
  await db.execute("UPDATE households SET verification_status='Rejected' WHERE household_id=?",[household]);
  await request('flood-reports','POST',form,token,403);
  await request('auth/me','GET',undefined,token,403);
  await request('auth/profile','PUT',profile,token,403);
  await request('auth/login','POST',{username,password:newPassword},undefined,403);
  await db.execute("UPDATE households SET verification_status='Verified' WHERE household_id=?",[household]);
  await db.execute("UPDATE residents SET record_status='Inactive' WHERE resident_id=?",[resident]);
  await request('flood-reports','POST',form,token,403);
  await db.execute("UPDATE residents SET record_status='Active' WHERE resident_id=?",[resident]);
  const refresh=await fetch(`http://localhost:${config.port}/api/auth/refresh`,{method:'POST',headers:{cookie:changed.cookie!}});
  assert.equal(refresh.status,200); token=(await refresh.json() as any).accessToken;
  await request('auth/me','GET',undefined,token);
  await request('auth/change-password','POST',{currentPassword:newPassword,newPassword:'AnotherPassword123'},token);
  await request('auth/login','POST',{username,password:newPassword},undefined,401);
  token=(await request('auth/login','POST',{username,password:'AnotherPassword123'})).data.accessToken;
  await db.execute('DELETE FROM resident_accounts WHERE user_id=?',[userId]);
  await request('auth/login','POST',{username,password:'AnotherPassword123'},undefined,403);
  await request('flood-reports','POST',form,token,403);
  await request('auth/me','GET',undefined,token,403);
  await db.execute('UPDATE users SET is_active=0 WHERE user_id=?',[userId]);
  await request('auth/me','GET',undefined,token,401);
  console.log('PASS: resident profile updates, own-record isolation, protected fields, input validation, duplicate protection, optional field clearing, reporter identity refresh, resident provisioning, validation, login, password changes, refresh, account privacy, staff isolation, trusted reporter identity and revoked eligibility.');
} finally {
  if(reportId){await db.execute('DELETE FROM flood_report_zones WHERE report_id=?',[reportId]);await db.execute('DELETE FROM flood_reports WHERE report_id=?',[reportId]);}
  await db.execute('DELETE FROM users WHERE username=? AND user_id<>?', [username,userId]);
  if(userId){await db.execute('DELETE FROM refresh_tokens WHERE user_id=?',[userId]);await db.execute('DELETE FROM password_reset_tokens WHERE user_id=?',[userId]);await db.execute('DELETE FROM resident_accounts WHERE user_id=?',[userId]);await db.execute('DELETE FROM users WHERE user_id=?',[userId]);}
  await db.execute('DELETE FROM residents WHERE resident_id=?',[otherResident]);
  await db.execute('DELETE FROM residents WHERE resident_id=?',[resident]);
  await db.execute('DELETE FROM households WHERE household_id=?',[household]);
  await db.execute('DELETE FROM zones WHERE zone_id=?',[zone]);
  await db.end();
}
