import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db} from './db.js';
import {config} from './config.js';
import {createAccessToken,createRefreshToken} from './auth.js';

assert.ok(['localhost','127.0.0.1'].includes(new URL(config.databaseUrl).hostname),'Use a local test database.');
const secretary=randomUUID(),zone=randomUUID(),household=randomUUID(),resident=randomUUID(),users:string[]=[];
const name=`Registration ${randomUUID()}`;
let reportId='',newResidentId='';
const request=async(path:string,method='GET',body?:unknown,token?:string,status=200,cookie?:string)=>{
  const response=await fetch(`http://localhost:${config.port}/api/${path}`,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{}) ,...(cookie?{cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});
  if(path==='auth/register' && status===201) assert.equal(response.headers.get('set-cookie'),null);
  const text=await response.text();assert.equal(response.status,status,`${method} ${path}: ${text}`);return text?JSON.parse(text):null;
};
try {
  await db.execute("INSERT INTO users(user_id,full_name,username,email,password_hash,role) VALUES(?,?,?,?,?,'Secretary')",[secretary,'Test Secretary',secretary,`${secretary}@example.test`,'Unused test credential']);
  const secretaryToken=createAccessToken({userId:secretary,username:secretary,role:'Secretary',credentialVersion:0});
  const [admins]=await db.query<any[]>("SELECT user_id,username,role,credential_version FROM users WHERE role='Super Admin' AND is_active=1 AND must_change_password=0 LIMIT 1");assert.ok(admins[0]);
  const admin=createAccessToken({userId:admins[0].user_id,username:admins[0].username,role:admins[0].role,credentialVersion:admins[0].credential_version});
  await db.execute('INSERT INTO zones(zone_id,zone_name,polygon_geojson) VALUES(?,?,?)',[zone,name,JSON.stringify({type:'Polygon',coordinates:[[[122.884,13.782],[122.886,13.782],[122.886,13.784],[122.884,13.784],[122.884,13.782]]]})]);
  await db.execute("INSERT INTO households(household_id,household_number,zone_id,address_line,head_of_household_name,verification_status) VALUES(?,?,?,?,?,'Verified')",[household,name,zone,'Colacling test address','Test head']);
  await db.execute("INSERT INTO residents(resident_id,household_id,full_name,date_of_birth,sex,address_line,contact_number) VALUES(?,?,?,'2000-01-01','Female','Colacling test address','09123456789')",[resident,household,name]);
  const input={fullName:name,username:`registration-${randomUUID()}`,email:`${randomUUID()}@example.test`,password:'SelfRegistration123',dateOfBirth:'2000-01-01',contactNumber:'09123456789',addressLine:'Colacling test address',householdNumber:name};
  await request('auth/register','POST',{...input,password:'weak'},undefined,400);
  await request('auth/register','POST',{...input,dateOfBirth:'2000-02-30'},undefined,400);
  await request('auth/register','POST',{...input,contactNumber:'-------'},undefined,400);
  const registered=await request('auth/register','POST',{...input,role:'Super Admin',status:'Approved',residentId:resident},undefined,201);
  assert.equal(registered.accessToken,undefined);assert.equal(registered.user,undefined);
  const [created]=await db.query<any[]>('SELECT user_id,role,must_change_password,last_login_at FROM users WHERE username=?',[input.username]);
  const userId=created[0].user_id;users.push(userId);
  assert.equal(created[0].role,'Resident');assert.equal(created[0].must_change_password,0);assert.equal(created[0].last_login_at,null);
  const identity={userId,username:input.username,role:'Resident' as const,credentialVersion:0};
  const token=createAccessToken(identity),oldRefresh=await createRefreshToken(identity);
  await request('auth/login','POST',{username:input.username,password:input.password},undefined,403);
  await request('auth/login','POST',{username:input.username,password:'wrong'},undefined,401);
  await request('auth/me','GET',undefined,token,403);
  await request('auth/change-password','POST',{currentPassword:input.password,newPassword:'ChangedPassword123'},token,403);
  await request('auth/refresh','POST',{},undefined,403,`refreshToken=${oldRefresh}`);
  const [pending]=await db.query<any[]>('SELECT status,contact_number FROM resident_registrations WHERE user_id=?',[userId]);assert.equal(pending[0].status,'Pending');assert.equal(pending[0].contact_number,input.contactNumber);
  await request('auth/register','POST',input,undefined,400);
  await request('resident-registrations','GET',undefined,undefined,401);
  await request('resident-registrations','GET',undefined,token,403);
  await request('resident-registrations/residents','GET',undefined,token,403);
  for(const path of ['users','residents','households','dashboard/summary','statistics/dss'])await request(path,'GET',undefined,secretaryToken,403);
  const lookup=await request(`resident-registrations/residents?search=${encodeURIComponent(name)}&sortBy=r.full_name`,'GET',undefined,secretaryToken);
  assert.equal(lookup.items[0].resident_id,resident);assert.equal(lookup.items[0].verification_status,'Verified');assert.equal(lookup.items[0].philsys_number,undefined);
  const queue=await request('resident-registrations?filter_status=Pending&sortBy=s.created_at','GET',undefined,secretaryToken);assert.ok(queue.items.some((r:any)=>r.user_id===userId));
  const report={locationText:'Colacling test address',incidentType:'Road Flooding',severityLevel:'Information',latitude:13.7828976,longitude:122.8852784,reporterName:'Forged'};
  await request('flood-reports','POST',report,token,403);
  const reviewPath=`resident-registrations/${userId}/review`,approve={status:'Approved',residentId:resident,confirmed:true,notes:'Identity and household checked.'};
  await request(reviewPath,'POST',approve,token,403);
  await request(reviewPath,'POST',{...approve,confirmed:false},secretaryToken,400);
  await db.execute("UPDATE households SET verification_status='Pending Verification' WHERE household_id=?",[household]);
  await request(reviewPath,'POST',approve,secretaryToken,400);
  await db.execute("UPDATE households SET verification_status='Verified' WHERE household_id=?",[household]);
  // Even an administrator linking the pending account does not approve it.
  await request(`users/${userId}`,'PUT',{fullName:name,username:input.username,email:input.email,role:'Resident',residentId:resident},admin,204);
  await request('auth/login','POST',{username:input.username,password:input.password},undefined,403);
  const [sessions]=await db.query<any[]>('SELECT COUNT(*) total FROM refresh_tokens WHERE user_id=?',[userId]);assert.equal(sessions[0].total,1,'Denied sign-in must not create a refresh session');
  await request(reviewPath,'POST',approve,secretaryToken);
  await request(reviewPath,'POST',approve,secretaryToken,409);
  const approvedLogin=await request('auth/login','POST',{username:input.username,password:input.password});
  const me=await request('auth/me','GET',undefined,approvedLogin.accessToken);assert.equal(me.registration.status,'Approved');assert.equal(me.resident.resident_id,resident);
  const [audit]=await db.query<any[]>('SELECT reviewed_by_user_id,reviewed_at FROM resident_registrations WHERE user_id=?',[userId]);assert.equal(audit[0].reviewed_by_user_id,secretary);assert.ok(audit[0].reviewed_at);
  reportId=(await request('flood-reports','POST',report,approvedLogin.accessToken,201)).reportId;
  const [reports]=await db.query<any[]>('SELECT reporter_user_id,reporter_name FROM flood_reports WHERE report_id=?',[reportId]);assert.equal(reports[0].reporter_user_id,userId);assert.equal(reports[0].reporter_name,name);
  const rejectedInput={...input,username:`registration-${randomUUID()}`,email:`${randomUUID()}@example.test`};
  await request('auth/register','POST',rejectedInput,undefined,201);
  const [rejectedRows]=await db.query<any[]>('SELECT user_id FROM users WHERE username=?',[rejectedInput.username]);const rejectedId=rejectedRows[0].user_id;users.push(rejectedId);
  await request(`resident-registrations/${rejectedId}/review`,'POST',approve,secretaryToken,400);
  await request(`resident-registrations/${rejectedId}/review`,'POST',{status:'Rejected',notes:''},secretaryToken,400);
  await request(`resident-registrations/${rejectedId}/review`,'POST',{status:'Rejected',notes:'Identity could not be validated.'},secretaryToken);
  await request('auth/login','POST',{username:rejectedInput.username,password:rejectedInput.password},undefined,403);
  await db.execute("UPDATE resident_registrations SET status='Rejected' WHERE user_id=?",[userId]);
  await request('auth/me','GET',undefined,approvedLogin.accessToken,403);
  const revokedRefresh=await createRefreshToken({...identity,credentialVersion:approvedLogin.user.credentialVersion});
  await request('auth/refresh','POST',{},undefined,403,`refreshToken=${revokedRefresh}`);
  await request('flood-reports','POST',report,approvedLogin.accessToken,403);
  const newInput={...input,fullName:'New '+name,username:`registration-${randomUUID()}`,email:`${randomUUID()}@example.test`};
  await request('auth/register','POST',newInput,undefined,201);
  const [newUsers]=await db.query<any[]>('SELECT user_id FROM users WHERE username=?',[newInput.username]);const newUserId=newUsers[0].user_id;users.push(newUserId);
  const newPath=`resident-registrations/${newUserId}/review`;
  const newResident={householdId:household,fullName:newInput.fullName,dateOfBirth:newInput.dateOfBirth,sex:'Female',addressLine:newInput.addressLine,contactNumber:newInput.contactNumber,priorityLevel:'Medium'};
  const createApproval={status:'Approved',newResident,confirmed:true,notes:'New identity and household verified; checked duplicates.'};
  await request('resident-registrations/households','GET',undefined,undefined,401);
  await request('resident-registrations/households','GET',undefined,approvedLogin.accessToken,403);
  const households=await request(`resident-registrations/households?search=${encodeURIComponent(name)}&sortBy=h.household_number`,'GET',undefined,secretaryToken);assert.equal(households.items[0].household_id,household);assert.equal(households.items[0].contact_number,undefined);
  await request(newPath,'POST',createApproval,approvedLogin.accessToken,403);
  await request(newPath,'POST',{...createApproval,confirmed:false},secretaryToken,400);
  await request(newPath,'POST',{...createApproval,residentId:resident},secretaryToken,400);
  await request(newPath,'POST',{...createApproval,newResident:{...newResident,sex:'Invalid'}},secretaryToken,400);
  await request(newPath,'POST',{...createApproval,newResident:{...newResident,contactNumber:'invalid'}},secretaryToken,400);
  await request(newPath,'POST',{...createApproval,newResident:{...newResident,fullName:name}},secretaryToken,409);
  await db.execute("UPDATE households SET verification_status='Pending Verification' WHERE household_id=?",[household]);
  const unavailable=await request(`resident-registrations/households?search=${encodeURIComponent(name)}&sortBy=h.household_number`,'GET',undefined,secretaryToken);assert.equal(unavailable.items.length,0);
  await request(newPath,'POST',createApproval,secretaryToken,400);
  const [noPartial]=await db.query<any[]>('SELECT resident_id FROM residents WHERE full_name=?',[newInput.fullName]);assert.equal(noPartial.length,0);
  await request('auth/login','POST',{username:newInput.username,password:newInput.password},undefined,403);
  await db.execute("UPDATE households SET verification_status='Verified' WHERE household_id=?",[household]);
  await request(newPath,'POST',createApproval,secretaryToken);
  const [added]=await db.query<any[]>('SELECT r.* FROM residents r JOIN resident_accounts a ON a.resident_id=r.resident_id WHERE a.user_id=?',[newUserId]);
  newResidentId=added[0].resident_id;assert.equal(added[0].household_id,household);assert.equal(added[0].full_name,newInput.fullName);assert.equal(added[0].priority_level,'Medium');assert.equal(added[0].record_status,'Active');
  await request(newPath,'POST',createApproval,secretaryToken,409);
  const newLogin=await request('auth/login','POST',{username:newInput.username,password:newInput.password});
  const newMe=await request('auth/me','GET',undefined,newLogin.accessToken);assert.equal(newMe.registration.status,'Approved');assert.equal(newMe.resident.resident_id,newResidentId);
  console.log('PASS: secretary adds and approves a new resident atomically, verified household lookup, input validation, duplicate protection, rollback, stale reviews and approved login.');
  console.log('PASS: self-registration validation, pending/rejected sign-in denial, no automatic session, stale access/refresh denial, approved login, role injection protection, secretary scope, private lookup, explicit approval, household eligibility, audit, duplicate reviews, rejected reporting and trusted reporter attribution.');
} finally {
  if(reportId){await db.execute('DELETE FROM flood_report_zones WHERE report_id=?',[reportId]);await db.execute('DELETE FROM flood_reports WHERE report_id=?',[reportId]);}
  for(const userId of users){await db.execute('DELETE FROM refresh_tokens WHERE user_id=?',[userId]);await db.execute('DELETE FROM resident_accounts WHERE user_id=?',[userId]);await db.execute('DELETE FROM users WHERE user_id=?',[userId]);}
  await db.execute('DELETE FROM users WHERE user_id=?',[secretary]);
  if(newResidentId)await db.execute('DELETE FROM residents WHERE resident_id=?',[newResidentId]);
  await db.execute('DELETE FROM residents WHERE resident_id=?',[resident]);
  await db.execute('DELETE FROM households WHERE household_id=?',[household]);
  await db.execute('DELETE FROM zones WHERE zone_id=?',[zone]);
  await db.end();
}
